export default {
  dbHost: 'localhost',
  dbPort: 3306,
  dbName: 'jasmin_alternating',
  dbUsername: 'bas',
  dbPassword: 'toor',

  port: process.env.PORT || 9009,
  JASMINE_RESTFULL_API: 'http://127.0.0.1:8080/secure',
  GEEZ_RESTFULL_API: 'https://api.geezsms.com/api',
  STORAGE_RESTFULL_API: 'http://localhost:8002/api',
  job_name: "A2pBULK_KONSO_IRC_01-2023-06-02",
  group_id: 'KONSO_IRC',
  progress: 0,
  msg: "Ajaylaa \nPirokiraameta raatoneta ahellaa shashakka Isho a kollissampateeta aafaa Xonso \nToollaaye Ihhalaatin \nAwta  Piisa Lankayya Etaa teykanta 3:40-4:00, Palawwa kalpta Etaa12:20-12:40 Arpaminji \nEffi Emmeeta 90.9 Olliyyi. \nAkka ishin kapannin tarpenin \nHellaa poraa oppan kahadan ka kolladan  iharmisamte ",
  billing_id: 397,
  user_id: 138,
  shortcode_id: 22,
  usr: 'geezp',
  pwd: 'geezp@321',
  from: 'IRC',
  token: 'N7tu3Iiamcv4B4X1XNRxBMdoVJvkEx3H',
  backendHost: 'https://api.geezsms.com',
  jwt: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvYXBpLmdlZXpzbXMuY29tXC9hcGlcL2xvZ2luIiwiaWF0IjoxNjc1NjY2MDg5LCJleHAiOjE2NzU2ODc2ODksIm5iZiI6MTY3NTY2NjA4OSwianRpIjoiaFJtWG51R25qR2VsNjhWMyIsInN1YiI6MTM4LCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.SNuRmzR0A3y_UnO6aM34664F757MjgewyDIQ6UnmE_w',
};
