export default {
  dbHost: 'localhost',
  dbPort: 3306,
  dbName: 'jasmin',
  dbUsername: 'root',
  dbPassword: '',

  port: process.env.PORT || 9009,
  JASMINE_RESTFULL_API: 'http://127.0.0.1:8080/secure',
  GEEZ_RESTFULL_API: 'https://api.geezsms.com/api',
  STORAGE_RESTFULL_API: 'http://localhost:8002/api',

  group_id: 'ALLE',
  progress: 0,
  msg: "Qawkaaro \nPorkiraame Raatunatte koro hxaseesay pana koro kollisay mi'aadhe noosi Qaluntettay gharssamti /nAhxkkadhdhekka a hayamtenku!\nKuyyanko K'aa'iththitona kallapte saathe 7:20 - 7:40 pana kuyyanko lunkonna  kallapte saathe 7:20 - 7:40 Raatune EF EM Jinkattay 87.8 pana 90.7 inti hola/hela saarppu",
  billing_id: 397,
  user_id: 138,
  shortcode_id: 22,
  usr: 'geezp',
  pwd: 'geezp@321',
  from: 'IRC',
  token: 'N7tu3Iiamcv4B4X1XNRxBMdoVJvkEx3H',
  backendHost: 'https://api.geezsms.com',
  jwt: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvYXBpLmdlZXpzbXMuY29tXC9hcGlcL2xvZ2luIiwiaWF0IjoxNjc0NTQ1MTkzLCJleHAiOjE2NzQ1NjY3OTMsIm5iZiI6MTY3NDU0NTE5MywianRpIjoicm9rMmlKUWViWjdNTUl0WCIsInN1YiI6MTM4LCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.atgS86D90v2hRESYlmKD4PoW5QQXIbO8b6P-fWw7EYQ',
};
