export default {
  dbHost: 'localhost',
  dbPort: 3306,
  dbName: 'jasmin_alternating',
  dbUsername: 'bas',
  dbPassword: 'toor',

  port: process.env.PORT || 9009,
  JASMINE_RESTFULL_API: 'http://127.0.0.1:8080/secure',
  GEEZ_RESTFULL_API: 'https://api.geezsms.com/api',
  STORAGE_RESTFULL_API: 'http://localhost:8002/api',
  job_name: "A2pBULK_test_bulk_2023-02-21",
  group_id: 'BULKTEST308',
  progress: 0,
  msg: "Ajaylaa \nPirokiraameta raatoneta ahellaa shashakka Isho a kollissampateeta aafaa Xonso \nToollaaye Ihhalaatin \nAwta  Piisa Lankayya Etaa teykanta 3:40-4:00, Palawwa kalpta Etaa12:20-12:40 Arpaminji \nEffi Emmeeta 90.9 Olliyyi. \nAkka ishin kapannin tarpenin \nHellaa poraa oppan kahadan ka kolladan  iharmisamte",
  billing_id: 397,
  user_id: 138,
  shortcode_id: 22,
  usr: 'geezp',
  pwd: 'geezp@321',
  from: 'IRC',
  token: 'N7tu3Iiamcv4B4X1XNRxBMdoVJvkEx3H',
  backendHost: 'https://api.geezsms.com',
  jwt: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvYXBpLmdlZXpzbXMuY29tXC9hcGlcL2xvZ2luIiwiaWF0IjoxNjc2OTY1NTU2LCJleHAiOjE2NzY5ODcxNTYsIm5iZiI6MTY3Njk2NTU1NiwianRpIjoicmZzU1l0T3NueTlqN21HNiIsInN1YiI6MTM4LCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.tsrCw33Si0DsP344kBlR63GGHyAO28l4NE6CNVlYW2Y',
};
